### ISSUE TITLE
Default Import Method or Ignore File or Dir Patterns

### ISSUE THREAD

**Issue by nkabbara** [kristijanhusak/vim-js-file-import#17]
Hello!

I have situation where the file select prompt is coming up when I don't want it to.

For example, I have a project where a  component definition is located is located in both, a `.js` file and a `.js.solution` file. gutentags is properly configured to ignore *.solution. But JFI provides a prompt when trying to go to definition.

I'm thinking of ways where JFI can be told not to show the prompt. Possible options:

1. If`gutentags_ctags_exclude` option is there, respect it and ignore these files as well.
2. Add an option to default to ctags or to file in case 2+ definitions are found
3. Add an option to ignore pattern (files and dirs) to JFI's file lookup.

Is there a similar feature in the pipeline or current ways to avoid the above from happening?

**Comment by kristijanhusak** [comment]
There are filters that apply to the `cmd` part of the tags (Regex part), more info here https://github.com/kristijanhusak/vim-js-file-import/blob/master/doc/vim-js-file-import.txt#L271.

I assume that doesn't cover case since you need to filter out filenames, not cmd parts of the tag. Does adding that to `wildignore` maybe help?

I can introduce this additional filtering by filename since we already have something.

**Comment by kristijanhusak** [comment]
Can you give me an example what you get in the prompt? Does it load the matching filename, or it finds tags?
It shouldn't find the tags if they are not part of the generated ctags, so I assume it's just a matching filename.

**Comment by nkabbara** [comment]
> Can you give me an example what you get in the prompt? Does it load the matching filename, or it finds tags?

Of course. 

Below is an example where when I do `<Leader>if` over `AutenticatedApp` I get the ctags and the filename in the prompt. I need a way to be able to ignore files with .solution and if possible certain directories.  Please see other example below image for why directories too.
 
![Ctags & File](https://user-images.githubusercontent.com/31865/78085903-9c601100-7379-11ea-9223-b7a525f67f0a.png)

Below is an example of having a test dir that contains the same filename. When I hit `<Leader>if` over useCallbackStatus() it pulls 3 sources, the right one, the one in the test dir and the .solution. If possible, I'd like to be able to configure it to ignore certain directories like __tests__ in image below.

![file-and-testdir](https://user-images.githubusercontent.com/31865/78086193-70915b00-737a-11ea-94d6-6e9a0f049278.png)

Finally (this might be a bug), I noticed that if I've configured gutentags to store tag files outside the project (using `g:gutentags_cache_dir`), the tag file will have absolute paths to files instead of project relative paths. This is causing JFI to prompt fo the same file twice, one by filename, and the other by ctag.  See below: 1 &  3 are the same file.

![same-file](https://user-images.githubusercontent.com/31865/78086550-8fdcb800-737b-11ea-943a-c52f21608cc4.png)

I hope this is useful. Please let me know if you have any questions or need me to debug something. Thanks again!

**Comment by kristijanhusak** [comment]
Just as I suspected.
I introduced new configuration variable, `g:js_file_import_filename_filters`.

In your case, setting it to this should do the trick:
```vimL
let g:js_file_import_filename_filters = ['js\.solution$', 'tests\/']
```
Note that it's regex, so that's why i escaped dot and slash.

For the multiple tags, that's something you need to configure in your vimrc with `set tags`. JFI doesn't search for any tag files, it just calls internal taglist() function that does this automatically.

Default value for `set tags` has a pattern that searches tags in the upper directories (see `:help file-searching`). In your case, setting it to `set tags=./tags` should do the trick. If not, play with that setting to make it work.

Let me know if the new filename filters work.

**Comment by kristijanhusak** [comment]
Just a note for duplicate entries in tags, someone else also reported it and i figured it out and fixed it. Give it a try without changing your `tags` value.

**Comment by nkabbara** [comment]
Nice! Both now working as expected! Thank you so much! You're the man!

**Comment by kristijanhusak** [comment]
Great! Closing.
