### ISSUE TITLE
Importing useRef 

### ISSUE THREAD

**Issue by KingOfCramers** [kristijanhusak/vim-js-file-import#27]
Hello, installed the package with Plug and everything seems to be OK, but I'm getting the fallback message when trying to import a simple `useRef` hook from React.

```
No tag found for word "useRef". Falling back to prompt.
Path to file or package name:
```

Is there a way that I've got to specify pulling from outside dependencies when the module is not in the current folder, or is that not possible? This also happens when I'm trying to import other modules, like ```moment.js```

Thanks for your work on the plugin!

**Comment by kristijanhusak** [comment]
Hi,

only things that are part of the tags file can be imported automatically. No javascript is being read or parsed.
Importing react would work because it's defined in package.json as dependency, but things that are exported from inside of dependency are not generated in tags file, thus not automatically importable.

For these situations you can just type in react, and after it prompts for full or partial, select partial, and you should get what you need.
