### ISSUE TITLE
Using :JsFileImport is really slow

### ISSUE THREAD

**Issue by AndrewVos** [kristijanhusak/vim-js-file-import#5]
I think it's because the plugin searches through `node_modules`. Maybe have an exclude path option or just ignore node_modules directly?

**Comment by kristijanhusak** [comment]
Does your ctags contains tags from node_modules?
Also, do you have ripgrep (rg), or ag (silversearcher) installed?

**Comment by AndrewVos** [comment]
> Does your ctags contains tags from node_modules?

No I have `node_modules` excluded for JS.

> Also, do you have ripgrep (rg), or ag (silversearcher) installed?

Nope, I don't use either. I use `git grep`. Maybe I could add support for `git grep` hmm.

**Comment by AndrewVos** [comment]
Oh I see that `ag` and `rg` are only used for `JsFindUsages`. I was using `JsFileImport`.

**Comment by AndrewVos** [comment]
Right, setting `wildignore` speeds things up considerably.

```
:set wildignore=/home/andrewvos/**/node_modules/**
```

Thanks! Do you know of any way to set it without the full path by the way?

**Comment by AndrewVos** [comment]
Oh and thanks for this great plugin, it's going to make life a lot easier for me!

**Comment by kristijanhusak** [comment]
Adding this should work out for any project:
```vimL
set wildignore+=*node_modules/**
```

note the `+=`. I'm appending to the wildignore variable, and i assume you should do the same, if you have some previous values for wildignore. If you don't, i recommend you to look into it and add some stuff that you don't need. Here's how my wildignore looks:

```vimL
set wildignore=*.o,*.obj,*~                                                    
set wildignore+=*.git*
set wildignore+=*.meteor*
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*cache*
set wildignore+=*logs*
set wildignore+=*node_modules/**
set wildignore+=*DS_Store*
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif
```

**Comment by AndrewVos** [comment]
Perfect! Thanks so much!

**Comment by stavalfi** [comment]
this should be added to the readme.

**Comment by kristijanhusak** [comment]
@stavalfi thanks for reminding. I added it: https://github.com/kristijanhusak/vim-js-file-import#performance-issues

**Comment by stavalfi** [comment]
it's not just performance issue. in case the user (like me) uses lerna\yarn workspaces so node_modules has symbolic links to folders, this plugin is confused because there are 2 options for every import: 

```
1. import x from 'path-to-y'
2. import x from 'path-to-node_modules/project1/path-to-y'
```


so it also fix this issue

**Comment by kristijanhusak** [comment]
Didn't knew that, I use mostly npm. Thanks!

**Comment by nkabbara** [comment]
Hi @kristijanhusak,

Anyway for me to debug why vim-js-file-import is slow? Namely, going to definitions (JsGotoDefinition) and also adding include (JsFileImport).

I have node_modules excluded from my ctags. I also have ripgrep installed. Another thing I noticed is if I do `C-]` (ctags go to definition), it's extremely fast. It's just when I do <Leader>if or <Leader>ig that things take about a second before results show up.

Thanks for the great plugin!

-Nash

**Comment by kristijanhusak** [comment]
Hi @nkabbara,

it's best to profile it with the built in profiler. Here are the steps:

1. Open up some js file where you want to do the import or goto definition
2. execute this command `:profile start jsfileimport.log`
3. then execute `:profile func *`
4. Execute the import or goto definition
5. execute command `:profile stop`

This will create `jsfileimport.log` in your project directory. Open it up and search all `js-file-import` occurrences to see what's happening.

If you want, you can upload it here so I can check it out. Just make sure to upload it as a file, since it can be really big.

`C-]` is much faster because it just goes to the first tag found. This plugin does a lot more besides that.

**Comment by nkabbara** [comment]
Hi @kristijanhusak,

Thank you for the great instructions!

I dug through [the logs](https://github.com/kristijanhusak/vim-js-file-import/files/4388673/jsfileimport.log) and from my limited experience in debugging vim, I'm leaning to think that `find` and` jsfileimport#utils#systemlist` might be part of the reason.

I ran the same find command in the project dir that JFI is running and it's taking about half a second.

```
$ time find .  -name 'FORMGROUP' -type d -not -path './node_modules/*' -o -name 'FormGroup' -type d -not -path './node_modules/*' -o -name 'form-group' -type d -not -path './node_modules/*' -o -name 'formGroup' -type d -not -path './node_modules/*' -o -name 'form_group' -type d -not -path './node_modules/*' -o -name 'formgroup' -type d -not -path './node_modules/*'

real	0m0.515s
user	0m0.063s
sys	0m0.447s
```

Even though find is provided with options to exclude node_modules, it's still searching through it. Here it is again with node_modules removed from my directory:

```
$ time find .  -name 'FORMGROUP' -type d -not -path './node_modules/*' -o -name 'FormGroup' -type d -not -path './node_modules/*' -o -name 'form-group' -type d -not -path './node_modules/*' -o -name 'formGroup' -type d -not -path './node_modules/*' -o -name 'form_group' -type d -not -path './node_modules/*' -o -name 'formgroup' -type d -not -path './node_modules/*'

real	0m0.024s
user	0m0.003s
sys	0m0.019s
```

I think we might want to use something along the lines of  ` -path ./node_modules -prune` instead of `-not` so find ignore node_modules?

**Comment by kristijanhusak** [comment]
@nkabbara I pushed some optimizations to the find command. Let me know if it's better. It should be since i'm excluding both .git and node_modules properly now.

**Comment by nkabbara** [comment]
@kristijanhusak Thank you so much. Much faster now.

On a somewhat related note, is there a way that you know of to map `gf` to execute `JsGotoDefinition` as a fallback if it can't find the file using the standard vim way?

Thanks man.

-Nash

**Comment by kristijanhusak** [comment]
@nkabbara `gf` or `<C-]>` ? `gf` is for jumping to a file path.

```

**Comment by kristijanhusak** [comment]
@nkabbara this should do the trick:

```vimL
function s:goto() abort
  try
    exe 'norm!gf'
  catch /.*/
    return feedkeys("\<Plug>(JsGotoDefinition)")
  endtry
endfunction

autocmd FileType javascript nmap <buffer><silent>gf :call <sid>goto()<CR>

```

You can do the same for `<C-]` by replacing `exe 'norm!gf'` with `exe 'tag '.expand('<cword>')`

**Comment by nkabbara** [comment]
@kristijanhusak nice! Thank you again!
